chatgpt:
  api-key: "API_KEY"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/ssafy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

    username: root
    password: "password"
  redis:
    port: 6379
    host: redis
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.naver.com
    port: 465
    username: "email"
    password: "password"
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
        ssl:
          enable: true


server:
  port: 8083

jwt:
  secret: "secret"
  expiration: 1800

OPENVIDU_URL: https://i9c110.p.ssafy.io:4443
OPENVIDU_SECRET: "secret"
